2025-02-19 19:59:40.07
dbb4ba2a
User
ERROR:root:SocketIO Error: handle_disconnect() takes 0 positional arguments but 1 was given
2025-02-19 19:59:40.68
dbb4ba2a
User
Zbh195n6dm9zKjY-AAAC: Sending packet OPEN data {'sid': 'Zbh195n6dm9zKjY-AAAC', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000, 'maxPayload': 1000000}
2025-02-19 19:59:40.68
dbb4ba2a
User
INFO:engineio.server:Zbh195n6dm9zKjY-AAAC: Sending packet OPEN data {'sid': 'Zbh195n6dm9zKjY-AAAC', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000, 'maxPayload': 1000000}
2025-02-19 19:59:40.88
dbb4ba2a
User
Zbh195n6dm9zKjY-AAAC: Received packet MESSAGE data 0
2025-02-19 19:59:40.88
dbb4ba2a
User
INFO:engineio.server:Zbh195n6dm9zKjY-AAAC: Received packet MESSAGE data 0
2025-02-19 19:59:40.88
dbb4ba2a
User
Zbh195n6dm9zKjY-AAAC: Sending packet MESSAGE data 0{"sid":"9HGevTPJeFbjgcT1AAAD"}
2025-02-19 19:59:40.88
dbb4ba2a
User
INFO:engineio.server:Zbh195n6dm9zKjY-AAAC: Sending packet MESSAGE data 0{"sid":"9HGevTPJeFbjgcT1AAAD"}
2025-02-19 19:59:40.88
dbb4ba2a
User
INFO:root:Client connected
2025-02-19 19:59:41.00
dbb4ba2a
User
Zbh195n6dm9zKjY-AAAC: Received request to upgrade to websocket
2025-02-19 19:59:41.00
dbb4ba2a
User
INFO:engineio.server:Zbh195n6dm9zKjY-AAAC: Received request to upgrade to websocket
2025-02-19 19:59:41.00
dbb4ba2a
User
[2025-02-19 17:59:41 +0000] [34] [ERROR] Error handling request /socket.io/?EIO=4&transport=websocket&sid=Zbh195n6dm9zKjY-AAAC
2025-02-19 19:59:41.00
dbb4ba2a
User
Traceback (most recent call last):
2025-02-19 19:59:41.00
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
2025-02-19 19:59:41.00
dbb4ba2a
User
self.handle_request(listener, req, client, addr)
2025-02-19 19:59:41.00
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
2025-02-19 19:59:41.00
dbb4ba2a
User
respiter = self.wsgi(environ, resp.start_response)
2025-02-19 19:59:41.00
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 19:59:41.00
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1536, in __call__
2025-02-19 19:59:41.00
dbb4ba2a
User
return self.wsgi_app(environ, start_response)
2025-02-19 19:59:41.00
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 19:59:41.00
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/flask_socketio/__init__.py", line 42, in __call__
2025-02-19 19:59:41.00
dbb4ba2a
User
return super().__call__(environ, start_response)
2025-02-19 19:59:41.00
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 19:59:41.00
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/middleware.py", line 63, in __call__
2025-02-19 19:59:41.00
dbb4ba2a
User
return self.engineio_app.handle_request(environ, start_response)
2025-02-19 19:59:41.00
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 19:59:41.00
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/socketio/server.py", line 434, in handle_request
2025-02-19 19:59:41.00
dbb4ba2a
User
return self.eio.handle_request(environ, start_response)
2025-02-19 19:59:41.00
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 19:59:41.00
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/server.py", line 286, in handle_request
2025-02-19 19:59:41.00
dbb4ba2a
User
packets = socket.handle_get_request(
2025-02-19 19:59:41.00
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 19:59:41.00
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/socket.py", line 92, in handle_get_request
2025-02-19 19:59:41.00
dbb4ba2a
User
return getattr(self, '_upgrade_' + transport)(environ,
2025-02-19 19:59:41.00
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 19:59:41.00
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/socket.py", line 151, in _upgrade_websocket
2025-02-19 19:59:41.00
dbb4ba2a
User
return ws(environ, start_response)
2025-02-19 19:59:41.00
dbb4ba2a
User
^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-02-19 19:59:41.00
dbb4ba2a
User
File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/engineio/async_drivers/gevent.py", line 54, in __call__
2025-02-19 19:59:41.00
dbb4ba2a
User
raise RuntimeError('The gevent-websocket server is not '
2025-02-19 19:59:41.00
dbb4ba2a
User
RuntimeError: The gevent-websocket server is not configured appropriately. See the Deployment section of the documentation for more information.
